// 2026-09-26
//
// Let "D-repeat of length n" denote the number having `n` digits, all of which
// are `D`.
//
// Each `d_i` can be analyzed independently (call it `d`).  It's basically just
// a case analysis.  If `d` is divisible by 25, 10, or 16, there are no
// solutions other than the trivial solution (the 0-repeat of length 1).
//
// Otherwise, first consider the case where `d` is not divisible by 2, 5, or 7.
// Then, the best solution will always be a 9-repeat.  To find the lengths of
// 9-repeats divisible by `d`, we need 10^n = 1 (mod d).  By the Fermat–Euler
// theorem, 10^{phi(d)} = 1 (mod d).  The smallest `n` for which 10^n = 1 (mod
// d), also known as the order of 10 in the multiplicative group of integers
// mod d, must divide phi(d).  (We need to precompute primes up to 10^7 so that
// we can efficiently factor integers up to 10^14 and thus calculate the phi
// function.) We can do better than trying all divisors of phi(d) because if
// 10^a = 1 and 10^b = 1 (mod d), it follows from successive divisions that
// 10^{gcd(a,b)} = 1 (mod d).  This means we can easily find the desired order
// by starting with n = phi(d) and, for each of its prime divisors, binary
// searching for the maximum power of it we can divide out from `n` while still
// giving 10^n = 1 (mod d).  (This binary search optimization probably isn't
// very important, but I had already finished writing it before I realized
// that.)
//
// If `d` is divisible by 7 but not 2 or 5, we must consider both 9-repeats and
// 7-repeats. For example, if K = 3 and d = 21, the best repeat is 777, and
// there is no 9-repeat divisible by `d` with fewer than 6 digits.  While if
// K = 6 and d = 63, the best repeat is 999999, and there is no 7-repeat with
// fewer than 9 digits divisible by `d`.  9-repeats are handled as above.  The
// set of 7-repeats divisible by `d` will also have lengths generated by some
// `m`, the length of the smallest member (this will follow from the analysis
// below).  To find `m`, consider that if a 7-repeat is divisible by `d` then
// the 1-repeat of the same length is divisible by d/7.  So first we find the
// minimum `n` with 10^n = 1 (mod d/7) using the technique from the previous
// paragraph.  Now a 1-repeat of length `n` may not contain enough factors of 3
// to be divisible by d/7.  Indeed, a 1-repeat of length `l` is divisible by a
// power of 3 only if `l` is divisible by that power of 3.  So m = lcm(n, 3^p)
// where 3^p is the largest power of 3 that divides d/7.
//
// Finally, all the remaining cases are that `d` is divisible by 2 or 5 but not
// both.  If `d` is divisible by 5, then every nontrivial solution is a
// 5-repeat; we look for 1-repeats that are divisible by d/5 analogously to the
// previous paragraph.  If `d` is divisible by 2, then the best nontrivial
// solution is always an 8-repeat and we look for 1-repeats that are divisible
// by d/2^p where d/2^p is odd.
#include <algorithm>
#include <iostream>
#include <unordered_map>
#include <utility>
#include <vector>
using namespace std;
using LL = long long;
using RepNum = pair<LL, int>;
vector<int> primes;
constexpr int MAXSIEVE = 1e7;
bool is_composite[MAXSIEVE + 1];
LL modexp(int b, LL e, LL mod) {
    if (e == 0) return 1;
    __int128 t = modexp(b, e / 2, mod);
    t = (t*t) % mod;
    if (e & 1) { t = (t*b) % mod; }
    return t;
}
/// Return the prime factorization of `n` as a list of (prime, exponent) pairs.
vector<pair<LL, int>> factorize(LL n) {
    vector<pair<LL, int>> result;
    for (const auto p : primes) {
        if (p*p > n) break;
        int e = 0;
        while (n % p == 0) { n /= p; e++; }
        if (e > 0) result.emplace_back(p, e);
    }
    if (n > 1) result.emplace_back(n, 1);
    return result;
}
/// Return the order of 10 in the multiplicative group of integers mod `d`.
/// `d` must not be divisible by 2, 5, or 7.
LL order10(LL d) {
    const auto pf = factorize(d);
    unordered_map<LL, int> tpf;
    LL tot = 1;
    for (const auto entry : pf) {
        tot *= entry.first - 1;
        for (int i = 1; i < entry.second; i++) tot *= entry.first;
        const auto entrypf = factorize(entry.first - 1);
        for (const auto entry2 : entrypf) tpf[entry2.first] += entry2.second;
        tpf[entry.first] += entry.second - 1;
    }
    LL powers[50] = {1};
    for (const auto pr : tpf) {
        const auto p = pr.first;
        const auto e = pr.second;
        for (int i = 1; i <= e; i++) powers[i] = powers[i - 1]*p;
        int l = 0, r = e;
        while (r > l) {
            const int m = (l + r) / 2;
            if (modexp(10, tot / powers[e] * powers[m], d) == 1) {
                r = m;
            } else {
                l = m + 1;
            }
        }
        tot = tot / powers[e] * powers[l];
    }
    return tot;
}
// Return the smallest multiple of `n` that has at least as many factors of 3 as
// `d` does.
LL lcm3(LL n, LL d) {
    LL p3 = 1;
    while (d % 3 == 0) { d /= 3; p3 *= 3; }
    while (n % p3 != 0) n *= 3;
    return n;
}
RepNum calc(int K, LL d) {
    if (d % 25 == 0 || d % 10 == 0 || d % 16 == 0) return {1, 0};
    if (d % 5 == 0) {
        const auto m = lcm3(order10(d / 5), d);
        return {m*(K/m), 5};
    } else if (d % 4 == 0) {
        while (d % 2 == 0) d /= 2;
        const auto m = lcm3(order10(d), d);
        return {m*(K/m), 8};
    } else if (d % 2 == 0) {
        const auto n = order10(d / 2);
        const auto m1 = lcm3(n, d);
        auto result = make_pair(m1*(K/m1), 8);
        if (d % 3 == 0) {
            const auto m2 = lcm3(n, d / 3);
            result = max(result, make_pair(m2*(K/m2), 6));
        }
        return result;
    } else if (d % 7 == 0) {
        const auto n = order10(d);
        const auto m = lcm3(order10(d / 7), d);
        return max(make_pair(n*(K/n), 9), make_pair(m*(K/m), 7));
    } else {
        const auto n = order10(d);
        return {n*(K/n), 9};
    }
}
void do_testcase() {
    int K, R; cin >> K >> R;
    RepNum result(1, 0);
    while (R--) {
        LL d; cin >> d;
        result = max(result, calc(K, d));
    }
    cout << result.first << ' ' << result.second << '\n';
}
int main() {
    for (int i = 2; i <= MAXSIEVE; i++) {
        if (is_composite[i]) continue;
        primes.push_back(i);
        if (i <= 3162) {
            for (int j = i*i; j <= MAXSIEVE; j += i) is_composite[j] = true;
        }
    }
    int T; cin >> T;
    while (T--) do_testcase();
}
